stages:
  - setup
  - unit-test
  - e2e-test

cache-node-modules:
  stage: setup
  image: node:alpine
  script:
    - cd frontend
    - npm ci
  artifacts:
    name: node_modules
    paths:
      - node_modules
    expire_in: 1h

unit-tests:
  stage: unit-test
  image: node:alpine
  script:
    - npm run test

#e2e-tests:
 # stage: e2e-test
  #image: node:alpine
  #script:
  #  - npm run test:e2e