stages:
  - build
  - test

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

before_script:
  - apt-get update -qy
  - apt-get install -y maven
  - apt-get install -y nodejs
  - apt-get install -y npm
  - cd backend

backend_build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean install

frontend_build:
  stage: build
  script:
    - cd ../frontend
    - npm install

backend_tests:
  stage: test
  script:
    - cd ../backend
    - mvn $MAVEN_CLI_OPTS test
  
#frontend_tests:
#  stage: test
#  script:
#    - cd ../frontend
#    - npm test
#  only:
#    - main
#    - dev