version: '3.8'
services:
  backend:
    build:
      context: ./
      dockerfile: backend/Dockerfile
    image: backend:latest
    container_name: dating-backend
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: test
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test"]
      interval: 5s
      timeout: 5s
      retries: 5