version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend:latest
    container_name: dating-backend
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: test
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
    healthcheck:
      test: wget --no-verbose --tries=1 --spider localhost:8080/actuator/health || exit 1
      interval: 60s
      retries: 5
      start_period: 5s
      timeout: 10s
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    container_name: db
    volumes:
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test"]
      interval: 5s
      timeout: 5s
      retries: 5

#  frontend:
#      build:
#        context: ./frontend
#        dockerfile: Dockerfile
#      image: frontend:latest
#      container_name: dating-frontend
#      ports:
#        - "3000:80"
#      healthcheck:
#        test: [ "CMD", "curl", "--fail", "http://localhost:80" ]
#        interval: 60s
#        retries: 5
#        start_period: 5s
#        timeout: 10s
#      depends_on:
#        backend:
#          condition: service_healthy